spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.tool.hbm2ddl=DEBUG

spring.datasource.url=jdbc:postgresql://localhost:5432/testdb
spring.datasource.username=testuser
spring.datasource.password=testpass

spring.mail.host=smtp.gmail.com
spring.mail.port=587

spring.mail.username=skshtlsdidrb@gmail.com
spring.mail.password=aihetvylpofwazbf
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.starttls.enable=true

spring.mvc.hiddenmethod.filter.enabled=true

server.tomcat.max-http-form-post-size=5MB
